"use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Nav, NavLink } from "@/components/Nav";
import { cn } from "@/lib/utils";
import Header from "@/components/layout/Header";
import { usePathname } from "next/navigation";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();

  console.log("path: ", pathname);
  return (
    <html lang="en">
      <head>
        <title>Title</title>
        <meta name="description" content="Description" />
      </head>
      <body
        className={cn(
          "min-h-screen h-full font-sans antialiased",
          inter.variable
        )}
      >
        {pathname != "/quiz" ? (
          <div className="mb-10">
            <Header />
          </div>
        ) : (
          ""
        )}
        {children}
      </body>
    </html>
  );
}
